# Dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - "*"
